name: "Release"

on:
  release:
    types: ["published"]

jobs:
  update_hacs_manifest:
    name: "Prepare release asset"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"

      - name: "Get version"
        id: "version"
        uses: "home-assistant/actions/helpers/version@master"

      - name: "Set manifest version number"
        run: |
          python3 ${{ github.workspace }}/.github/update_hacs_manifest.py \
            --version ${{ steps.version.outputs.version }}

      - name: "Create zip"
        run: |
          cd custom_components/watersmart
          zip watersmart.zip -r ./

      - name: "Upload zip to release"
        uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: "./custom_components/watersmart/watersmart.zip"
          asset_name: "watersmart.zip"
          tag: "${{ github.ref }}"
          overwrite: true
