name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 30
          days-before-close: 5
          stale-issue-label: "stale"
          exempt-issue-labels: "no-stale,help-wanted"
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale"
          stale-issue-message: >
            There hasn't been any activity on this issue recently. To keep the
            number of open issues under control, we have to clean some of the
            old issues, as many of them have already been resolved with the
            latest updates.

            Please make sure to update to the latest WaterSmart version and
            check if that solves the issue. Let us know if that works for you by
            adding a comment ðŸ‘

            This issue has now been marked as stale and will be closed if no
            further activity occurs. Thank you for your contributions.
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. This
            pull request has been automatically marked as stale because of that
            and will be closed if no further activity occurs within 7 days.

            If you are the author of this PR, please leave a comment if you want
            to keep it open. Also, please rebase your PR onto the latest dev
            branch to ensure that it's up to date with the latest changes.

            Thank you for your contribution!
